require('elicatza.plugins')     -- ./lua/elicatza/plugins.lua
require('elicatza.options')     -- ./lua/elicatza/options.lua
require('elicatza.keymaps')     -- ./lua/elicatza/keymaps.lua
require('elicatza.nvim-cmp')    -- ./lua/elicatza/nvim-cmp.lua
require('elicatza.delsp')       -- ./lua/elicatza/delsp.lua
require('elicatza.lsp')         -- ./lua/elicatza/lsp.lua
require('elicatza.treesitter')  -- ./lua/elicatza/treesitter.lua
require('elicatza.telescope')   -- ./lua/elicatza/telescope.lua
require('elicatza.gitsigns')    -- ./lua/elicatza/gitsigns.lua
require('elicatza.snippets')    -- ./lua/elicatza/snippets/init.lua
require('elicatza.feline')      -- ./lua/elicatza/feline/init.lua
require('elicatza.orgmode')     -- ./lua/elicatza/orgmode.lua
