#!/bin/sh

killall picom
picom &
xbindkeys
# feh --bg-fill --randomize ~/.local/share/feh-wallpapers/
feh --bg-scale --no-fehbg --randomize ~/.local/share/feh-wallpapers/

killall polybar
$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "#282c34"
bspc config focused_border_color "#b16286"
bspc config presel_feedback_color "#98c379"

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Evince desktop='^4' follow=on state=tiled
bspc rule -a mpv desktop='^4' follow=on state=tiled
bspc rule -a Sxiv desktop='^4' follow=on state=tiled

