#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
        for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
                [ -x "$f" ] && . "$f"
        done
        unset f
fi


setxkbmap -layout "us(intl)"
xmodmap $HOME/.config/X11/custom-dvorak-no
[[ -f ~/.config/X11/xresources ]] && xrdb -merge ~/.config/X11/xresources
xrbd -merge ~/.config/X11/xresources
exec bspwm

